import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import LayoutWrapper from "@/components/LayoutWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CookiesProvider>
      <ReactQueryProvider>
        <html lang="en">
          <body className={inter.className}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </body>
        </html>
      </ReactQueryProvider>
    </CookiesProvider>
  );
}
